name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '**'
  pull_request:
    branches: [main, dev, stage]

jobs:
  UnitTest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Determine output folder
      id: set_output_folder
      run: |
        if [[ $GITHUB_REF_NAME == "main" ]]; then
          echo "output_folder=prod" >> $GITHUB_ENV
        elif [[ $GITHUB_REF_NAME == "stage" ]]; then
          echo "output_folder=stage" >> $GITHUB_ENV
        elif [[ $GITHUB_REF_NAME == "dev" ]]; then
          echo "output_folder=dev" >> $GITHUB_ENV
        else
          echo "Unknown branch: $GITHUB_REF_NAME"
          exit 1
        fi

    - name: Run tests with coverage
      run: |
        dynamic_results_path="test_results/${{ env.output_folder }}"
        mkdir -p $dynamic_results_path
        PYTHONPATH=$(pwd) python -m coverage run --source=src -m unittest discover -v tests/
        coverage report > $dynamic_results_path/latest_report.log
        coverage report >> $dynamic_results_path/$(date '+%Y-%m-%d_%H-%M-%S')_report.log  

    - name: Upload report to Azure
      uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      with:
        source_folder: 'test_results/${{ env.output_folder }}'
        destination_folder: 'osw-quality-metric-service/${{ env.output_folder }}/${{ github.repository }}/unit_test_results'
        connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        container_name: 'reports'
        clean_destination_folder: false
        delete_if_exists: false
